services:
  - type: web
    name: cbo-awareness
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn cbo_project.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: DATABASE_URL
        fromDatabase:
          name: cbo-db
          property: connectionString

databases:
  - name: cbo-db
    plan: free
